name: Python CI

on:
    push:
        branches:
            - mian
    pull_request:
        branches:
            -main

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            -   name: Check out code
                uses: action/checkout@v2

            -   name: Setup up Python
                uses: actions/setup-python@v2
                with: 
                    python-version: '3.8'
            
            -   name: Install dependencies
                run: |
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt
            
            -   name: Run tests
                run: pytest
                    
                    

        
